name: backend_cleanair
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.0
